version: '3'
services:
  aq54prod:
    build:
      context: ./servers/app
      dockerfile: Dockerfile
    image: aq54-prod
    container_name: aq54-prod
    restart: unless-stopped
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./servers/app:/home/node/app
      -  distapp:/home/node/app/aq54

    links:
     - aq54frontend
    depends_on:
      - aq54frontend

    networks:
      - aq54


  aq54doc:
    build:
      context: ./servers/docs
      dockerfile: Dockerfile
    image: aq54doc
    container_name: aq54doc
    restart: unless-stopped
    environment:
      - PORT=8001
      - HOST=0.0.0.0
    ports:
      - 8001:8001
    links:
      - aq54frontend
    depends_on:
      - aq54frontend
    volumes:
        - codedoc:/home/node/app/documentation
    networks:
      - aq54

  aq54frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: aq54frontend
    container_name: aq54frontend
    volumes:
      - distapp:/home/node/app/distapp
      - codedoc:/home/node/app/documentation


    networks:
      - aq54

volumes:
    distapp:
    codedoc:

networks:
  aq54:















