version: '3'
services:
  aq54:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: aq54
    container_name: aq54
    restart: unless-stopped
    environment:
      - PORT=3000
    ports:
      - 3000:3000

  aq54doc:
    build:
      context: ./docs
      dockerfile: Dockerfile
    image: aq54doc
    container_name: aq54doc
    restart: unless-stopped
    environment:
      - PORT=8080
    ports:
      - 8080:8080
 




